[workspace]
members = [
    "client",
    "server",
    "shared",
    "examples/server",
    "examples/client/wasm_bindgen",
    "examples/client/miniquad",
    "examples/client/miniquad/dev_http_server"
    ]